version: "3"
services:
  redis:
    image: redis:latest
    container_name: grouping-redis
    
  mysql:
    image: mysql:latest
    container_name: grouping-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: groupings
      MYSQL_USER: covengers
      MYSQL_PASSWORD: convengers
    volumes:
      - /Users/이중혁/datadir:/var/lib/mysql # For Window Test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  